<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Form.aspx.cs" Inherits="KnockoutWebformWithController0102.Form" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
        $(function(){
            $("#tabs").tabs();
        });
    </script>
    <style>
        #tabs ul{
            display:flex;
            list-style:none;
            justify-content:space-evenly;
            background-color:#012970;
            padding:20px;
            
        }
        #tabs{
            
            padding:20px;
        }
        a{
            text-decoration:none;
            color:white;
            font-weight:600;
            font-size:20px;
            font-family: sans-serif;
        }
        #tabs1,#tabs2{
            background-color:#0c0d12;
            color:white;
            padding:20px;
            font-family:sans-serif;
            font-weight:500;
            line-height:30px;
        }
        .txbox{
            width:200px;
            height:30px;
        }
        .button1{
            background-color:#0c533d;
            color:white;
            width:90px;
            height:35px;
        }
        .gv{
            font-size:20px;
            
        }
        .gvIn{
            padding:10px;
        }
    </style>
</head>
<body>
    <div id="tabs">
        <ul>
            <li><a href="#tabs1">Insert</a></li>
            <li><a href="#tabs2">Display</a></li>
        </ul>
        <div id="tabs1">
        <form id="form1" runat="server">
        <div>
            <asp:Label ID="NameLabel" runat="server" Text="Enter Name: "></asp:Label><br />
            <asp:TextBox ID="NameText" runat="server" CssClass="txbox"></asp:TextBox><br /><br />
            <asp:Label ID="AgeLabel" runat="server" Text="Enter Age: "></asp:Label><br />
            <asp:TextBox ID="AgeText" runat="server" CssClass="txbox"></asp:TextBox><br /><br />
            <asp:Label ID="GenderLabel" runat="server" Text="Enter your gender: "></asp:Label><br />
            <asp:TextBox ID="GenderText" runat="server" CssClass="txbox"></asp:TextBox><br /><br />
            <asp:Label ID="AddressLabel" runat="server" Text="Enter Address: "></asp:Label><br />
            <asp:TextBox ID="AddressText" runat="server" CssClass="txbox"></asp:TextBox><br /><br />
            <asp:Button ID="FormButton" runat="server" Text="Submit" OnClick="Clickedbutton"  CssClass="button1"/><br /><br />
        </div>
    </div>
    <div id="tabs2">
            <asp:GridView ID="grid1" runat="server" CssClass="gv" AutoGenerateColumns="false"  AutoGenerateEditButton="True" AutoGenerateDeleteButton="true" DataKeyNames="id" OnRowEditing="edithere" OnRowDeleting="deletehere" OnRowDeleted="RowDeleted">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" />
                    <asp:BoundField DataField="Age" HeaderText="Age" />
                    <asp:BoundField DataField="Gender" HeaderText="Gender" />
                    <asp:BoundField DataField="Address" HeaderText="Address" />
                </Columns>
            </asp:GridView>
            
    </div>
    </div>
    <asp:label ID="Message" forecolor="Red" runat="server"/>
    
        </form>
</body>
</html>
